import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency, formatDate } from './utils';

export const exportToCSV = (data: any[], filename: string) => {
  if (data.length === 0) return;

  const headers = Object.keys(data[0]).join(',');
  const rows = data.map(obj => 
    Object.values(obj).map(val => `"${val}"`).join(',')
  ).join('\n');

  const csvContent = `data:text/csv;charset=utf-8,${headers}\n${rows}`;
  const encodedUri = encodeURI(csvContent);
  const link = document.createElement("a");
  link.setAttribute("href", encodedUri);
  link.setAttribute("download", `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportCustomerLedgerPDF = (customer: any, transactions: any[], storeName: string) => {
  const doc = new jsPDF();

  // Header - Aadaya Branding
  doc.setFontSize(22);
  doc.setTextColor(255, 107, 0); // #FF6B00
  doc.text('AADAYA AI CFO', 105, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('Smart Udhaar Ledger & Finance Report', 105, 26, { align: 'center' });

  // Store & Customer Info
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold');
  doc.text(`Store: ${storeName}`, 20, 40);
  
  doc.setFont('helvetica', 'normal');
  doc.text(`Customer: ${customer.name}`, 20, 48);
  doc.text(`Phone: ${customer.phone}`, 20, 54);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 150, 40);

  // Summary Box
  doc.setDrawColor(255, 107, 0);
  doc.setFillColor(255, 248, 240);
  doc.roundedRect(140, 45, 50, 20, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.text('Total Balance Due', 145, 52);
  doc.setTextColor(220, 38, 38); // Red
  doc.text(formatCurrency(customer.currentBalance), 145, 60);

  // Table
  autoTable(doc, {
    startY: 70,
    head: [['Date', 'Description', 'Type', 'Amount']],
    body: transactions.map(t => [
      formatDate(t.createdAt),
      t.description,
      t.type,
      formatCurrency(t.amount)
    ]),
    headStyles: { fillColor: [255, 107, 0] },
    alternateRowStyles: { fillColor: [255, 248, 240] },
    margin: { top: 70 },
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by Aadaya AI - Helping ${storeName} grow with transparency. Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
  }

  doc.save(`${customer.name}_Ledger_${new Date().toISOString().split('T')[0]}.pdf`);
};


